version: '3.8'

services:
  app:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: ["mvn", "spring-boot:run"]

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
