spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
